name: nakul_dev
description: "Hi, I'm Nakul, a computer engineer passionate about building innovative tech solutions."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  timeline_tile: ^2.0.0
  url_launcher: ^6.3.0
  auto_size_text: ^3.0.0
  scrollable_positioned_list: ^0.3.8
  google_nav_bar: ^5.0.6
  flutter_map_cancellable_tile_provider: ^3.0.2
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
     - assets/ss/qrcode.jpg
     - assets/ss/appleMusic.jpg
     - assets/ss/calc.jpg
     - assets/ss/ticTac.jpg
     - assets/ss/toDo.jpg
     - assets/ss/stopWatch.jpg
     - assets/ss/weather.jpg
     - assets/ss/portWeb.jpg
     - assets/i.png
     - assets/pfp2.png
     - assets/book.png
     - assets/emoji/Airplane.png
     - assets/emoji/Book.png
     - assets/emoji/Brain.png
     - assets/emoji/Gym.png
     - assets/emoji/Magnifier.png
     - assets/emoji/Moon.png
     - assets/svg/blender.svg
     - assets/svg/cpp.svg
     - assets/svg/css.svg
     - assets/svg/dart.svg
     - assets/svg/figma.svg
     - assets/svg/flutter.svg
     - assets/svg/html.svg
     - assets/svg/java.svg
     - assets/svg/javascript.svg
     - assets/svg/mysql.svg
     - assets/svg/python.svg
     - assets/svg/framer.svg
     - assets/svg/x.svg
     - assets/svg/linkedin.svg
     - assets/svg/instagram.svg
     - assets/svg/hackerrank.svg
     - assets/svg/github.svg
     - assets/svg/404.svg
     - assets/svg/email.svg

